### ISSUE TITLE
Sometimes montage enter in a loop of photographs

### ISSUE THREAD

**Issue by distriker** [hatnote/montage#8] opened 2016-10-11 23:31 UTC
Hi! First of all thank you for the tool. We, a group of users of Wikimedia Spain, are feeling a problem. 

When we have skip 5-15 photographs it increase the possibility of enter in a loop of the same photographs and it makes impossible to progress. When it happens we have to refresh the page and skip again the photographs skipped, but after 2-4 photographs skipped the error persists and we have to refresh again. A loop very annoying. We have detect that it often happens when we have skipped 12 photographs, perhaps it could help you.

I don't know if its could help you to solve it, but I paste here the error that shows in the Firefox console:
```
"Error: image is undefined
getImageName@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15:69:24459
anonymous/fn@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15 line 13 > Function:2:395
inputsWatchDelegate/<@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15:10:863
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15:10:16748
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15:10:19215
timeout/timeoutId<@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15:11:59
completeOutstandingRequest@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15:7:7039
Browser/self.defer/timeoutId<@https://tools.wmflabs.org/montage-beta/dist/bundle.min.js?v=16.10.15:7:10168
"
```

I think that error is the same or similar to another issue, _Error: image is undefined_ #6.

Thanks in advance and good luck solving it!

Regards, Iván

**Comment by mahmoud** [comment] 2016-10-11 23:37
Hi Iván, thank you for using montage and thank you for the detailed report! You are correct, currently skipping is implemented as a front-end only feature, intended to sample just a small number of photographs before voting. Long-term we are planning a back-end feature to enable more skipping and configuration for coordinators. Due to the high demand for features, it is unlikely we will get to it for this Wiki Loves Monuments, but we hope to have it for the next contest.

For #6 I think that is more front-end/@yarl's domain of expertise.

Thanks again! Keep the good reports coming :)

Mahmoud

**Comment by distriker** [comment] 2016-10-11 23:45
Thank you for your fast reply @mahmoud! But @yarl assign #6 to himself, no? It is only to confirm that the "Error: image is undefined" could be solve for that edition.

And one question more, if we have ideas to share with you to improve the tool, can I post it like an issue here or do you have a specific website to share it?

Regards, Iván

**Comment by mahmoud** [comment] 2016-10-11 23:49
Currently we are accepting feature requests and bug reports both here and [on the Wikimedia phabricator](https://phabricator.wikimedia.org/tag/montage/). Here you will get a higher chance of direct response from myself and other Hatnote developers. On phabricator you get a higher chance of long-term support of WLM organizers (they'll keep bugging us until we close issues :) ). Overall I think they prefer phabricator, but if you find GitHub easier to the point that you will report more, feel free to contact us here.

**Comment by revi** [comment] 2016-10-14 15:30
Hi,

I'm reviewing all of the files without skipping anything but I seem to be facing same images over and over again. Any ideas? Do I need to produce more information? (It seem to be random... anyway.)

**Comment by yarl** [comment] 2016-10-14 19:17
Honestly, I'm not sure what can be a problem now...
1. Front-end part was rewritten two days ago and now should work properly.
2. Is it possible that backend provides images that are already rated?

@revi: I know it can be hard, but can you observe IDs of images (eg. `Image #31162`). If image and image ID are duplicated that means something is wrong with Montage. But maybe people uploaded a lot of similar photos? During testing one campaign I saw nearly the same image at least three times.

**Comment by mahmoud** [comment] 2016-10-14 23:24
I just checked the backend, and my queries show neither Spain nor South Korea (revi's WLM) have duplicate tasks. 

In a bit of frontend testing on dev, when I rated very very quickly, it seemed that not all votes got through, which makes me think that some error may have gotten the app into a funky state where it wouldn't upload the votes, so that the tasks were not seen as completed from the backend. We've got 283,000 ratings though, so it's not like this is happening to everyone :)

We will continue to debug!

**Comment by revi** [comment] 2016-10-15 05:41
Image #174047
Image #173298
Image #173440
Image #174197
Image #173237
Image #173318
I seem to be stuck at these images... I tried with Google Chrome 53 at previous time and FireFox 48.0.2 when I was retrying.

**Comment by mahmoud** [comment] 2016-10-15 17:19
Just a quick update, last night we did some deep debugging and found the root cause. @yarl is working on a fix as we speak and we'll keep you posted here.

**Comment by yarl** [comment] 2016-10-16 13:48
Front-end should be finally fixed in ver. 16.10.20, it now live on beta.

**Comment by revi** [comment] 2016-10-17 03:51
Reviewed about 3-400 images in a row and it seems no (I think I saw one or two but that seem to have different image#) duplicates now.

**Comment by mahmoud** [comment] 2016-10-17 17:33
That's great! Yes, we pushed a few fixes, and I think this is resolved. Feel free to re-open (or open a new issue) if you run into more problems. Thanks everyone for your great reports!

**Closed by mahmoud** 2016-10-17 17:33 UTC
