### ISSUE TITLE
* empty page * after login

### ISSUE THREAD

**Issue by alchimista** [hatnote/montage#249] opened 2024-12-15 11:42 UTC
After login all i'm getting is an almost blank page, without information regarding my account or even past rounds or campaigns.
Tested on firefox 133 and chromium 131.0.6778.85, ubuntu version.

![Captura de ecrã de 2024-12-15 11-37-43](https://github.com/user-attachments/assets/dd8acb75-2827-4d85-9883-9a4ee39c9607)

**Comment by CiellB** [comment] 2024-12-15 12:35
I also only get empty pages for direct campaign links.

**Comment by Jayprakash-SE** [comment] 2024-12-15 14:42
Hi @alchimista, Can you record the error in https://jam.dev/ by chromium browser? I need recording + web logs to debug more. Thanks in advance.

**Comment by alchimista** [comment] 2024-12-15 15:23
@Jayprakash-SE while I was recording with jam, seems that the problem is no more active, I now see the campaigns and can vote in the open ones.

Neverless, seems I'm not able to create a new round. I have the button, but clicking on it does nothing. I don't see a button to close the round in order to create a new one, i'm not sure if that's the problem. 

jam file: [https://jam.dev/c/583382cd-17cb-4103-9efa-3cafe5c4092d](https://jam.dev/c/583382cd-17cb-4103-9efa-3cafe5c4092d)

**Comment by CiellB** [comment] 2024-12-16 16:02
@Jayprakash-SE 3 out of 9 jury members from the WLM-international jury are also reporting empty pages. 
Even though at least one has finished all his tasks in this round, there should at least be an active campaign assigned to them visible on the page. 
![image(1)](https://github.com/user-attachments/assets/c6f90bd6-559e-498d-8e13-cddbe21d1d11)

**Comment by lgelauff** [comment] 2024-12-16 19:12
The page `/campaign/<campaign-name>` is a page for coordinators. If you're a juror, I would expect that page to give either a permissions error (and redirect them to the main dashboard or, preferably, to the active round if any). If you're coordinator, the page should work (I don't know how it plays out if you're both?).

**Comment by fjmustak** [comment] 2024-12-16 20:48
https://jam.dev/c/2a95e5d9-fe0d-4f8f-80d5-251872c1715f

**Comment by lgelauff** [comment] 2024-12-16 20:53
> https://jam.dev/c/2a95e5d9-fe0d-4f8f-80d5-251872c1715f

Can you confirm you do see the campaign listed if you navigate to https://montage.toolforge.org/#/ ?

**Comment by fjmustak** [comment] 2024-12-16 20:58
> > https://jam.dev/c/2a95e5d9-fe0d-4f8f-80d5-251872c1715f
> 
> Can you confirm you do see the campaign listed if you navigate to https://montage.toolforge.org/#/ ?

@lgelauff I only see a blank screen, even if I'm going to the top level.  
On a fresh browser, sign in works, but then it's a blank screen again.
![image](https://github.com/user-attachments/assets/9f0933bf-fe66-4c26-b76d-4e2385264644)
![image](https://github.com/user-attachments/assets/71f523ea-2834-4418-ad08-ba79cef69723)

**Comment by lgelauff** [comment] 2024-12-16 21:02
> > > https://jam.dev/c/2a95e5d9-fe0d-4f8f-80d5-251872c1715f
> > 
> > 
> > Can you confirm you do see the campaign listed if you navigate to https://montage.toolforge.org/#/ ?
> 
> @lgelauff I only see a blank screen, even if I'm going to the top level. On a fresh browser, sign in works, but then it's a blank screen again. ![image](https://private-user-images.githubusercontent.com/22055200/396266156-9f0933bf-fe66-4c26-b76d-4e2385264644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzODMxODYsIm5iZiI6MTczNDM4Mjg4NiwicGF0aCI6Ii8yMjA1NTIwMC8zOTYyNjYxNTYtOWYwOTMzYmYtZmU2Ni00YzI2LWI3NmQtNGUyMzg1MjY0NjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDIxMDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNDRjMmYwMjc2ZWIxZDRkNDhmNzk5ODA1NmQ3NzI1ZDkxMzgzYTVjNTdiYjZmMzQ4NDcyNzZhYjRlMTQ5NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rCICpBtvqAaDnBHRMQ5d5gRhK9hD6ka__A3gfVF6Hkw) ![image](https://private-user-images.githubusercontent.com/22055200/396266430-71f523ea-2834-4418-ad08-ba79cef69723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzODMxODYsIm5iZiI6MTczNDM4Mjg4NiwicGF0aCI6Ii8yMjA1NTIwMC8zOTYyNjY0MzAtNzFmNTIzZWEtMjgzNC00NDE4LWFkMDgtYmE3OWNlZjY5NzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDIxMDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NWRkZGQzYTQ1MzQwOTU5MTU4NTI2YTg4MTIzZWJmNGI0ZGEwNDE4NTNmMTliNjRkN2IzZGJlMjA3NDdhM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5vNlxj55rlwU4LFUnmhvmXQ5SA4DUWiDsDWZna9ISkE)

Hmm, that is odd. Could you share a jam file for the top level as well? Thanks!

**Comment by fjmustak** [comment] 2024-12-16 21:21
Jam for top level 
https://jam.dev/c/19bb5487-d5c6-43ad-86fd-5992d6094aca

**Comment by lgelauff** [comment] 2024-12-16 21:49
> Jam for top level https://jam.dev/c/19bb5487-d5c6-43ad-86fd-5992d6094aca

Thank you! From the recording, it looks like this is not even managing to log you in.

**Comment by Jayprakash-SE** [comment] 2024-12-16 23:08
> Jam for top level https://jam.dev/c/19bb5487-d5c6-43ad-86fd-5992d6094aca

Hi @fjmustak , Can you record the same with browser refresh as Jam could not record log in this just 2 seconds.

**Comment by Jayprakash-SE** [comment] 2024-12-17 00:30
Hi @alchimista and @fjmustak, Can you try again and record the Jam once again?

Thanks in advance.

**Comment by fjmustak** [comment] 2024-12-17 08:26
It appears the issue is now resolved.
Thanks!

**Comment by lgelauff** [comment] 2024-12-18 23:11
Thanks for confirming! Closing the issue for now - if someone is still experiencing it, please open a new issue with a reference to this one.

**Closed by lgelauff** 2024-12-18 23:11 UTC
